Feature/sign up page
jetbase-io/nestjs-react-starter-app pull request #9
Opened 2022-06-13 11:59 UTC by nadyrbek97

https://trello.com/c/x2kgIkdb/8-sing-up-page

2022-06-14 11:47 UTC, seregaskirev requested changes

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/components/Header/index.tsx
> +            )}
let's avoid repeating code

I see that
```
<ul className="flex flex-col lg:flex-row list-none ml-auto">
```
should be out of if-else because we type two times

and
```
<li className="nav-item">
                <a className="px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75" href="#pablo">
                  Sign Out
                </a>
              </li>
```
can be a component because code is too same


for example,
```
const LINKS = [
  { tag: 'a', text: 'Sign Out', to: '#pablo', isVisible: isAuthenticated  },
  { tag: 'Link', text: 'Sign In', to: '/signIn', isVisible: !isAuthenticated },
  { tag: 'Link', text: 'Sign Up', to: ''/signUp', isVisible: !isAuthenticated },
];

<ul className="flex flex-col lg:flex-row list-none ml-auto">
   {LINKS.map({tag, text, to, isVisible} => isVisible && <HeaderLink tag={tag} text={text} to={to} />)}
</ul>
```

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/components/Header/index.tsx
> +
let's use destructing
```
const Header: FC<HomePageProps> = ({ isAuthenticated }) => {
```

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/components/Header/index.tsx
> +
need to add PropTypes

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/store/http/http-common.ts
> +  baseURL: "http://localhost:7000/api",
let's move ```http://localhost:7000``` to env variable

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/store/models/user.ts
> +    }
use destructing more
```
setTokens(state, { accessToken, refreshToken }) => {...state, accessToken, refreshToken};
```

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/store/models/user.ts
> +        let response = await http.post('auth/signUp', {
let's move all route constants to the separate file in constants folder
'auth/signUp'

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/store/models/user.ts
> +        localStorage.setItem('refreshToken', response.data.refreshToken);
I think accessToken and refreshToken should be saved after sign in, not sign up
After sign up we should redirect app to sign in page

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/pages/SignUpPage/index.tsx
> +import {RootState, Dispatch} from "../../store/store";
please, use eslint, there no spaces

2022-06-14 11:47 UTC, seregaskirev commented on frontend/src/pages/SignUpPage/index.tsx
> +import {RootState, Dispatch} from "../../store/store";
and prettier, different quotes

2022-06-14 11:51 UTC, nadyrbek97 commented on frontend/src/components/Header/index.tsx
> +            )}
ok, thanks for responding! I will do all needed refactoring :)

2022-06-16 08:11 UTC, seregaskirev approved these changes

2022-06-16 16:13 UTC, merged